# Site settings
name: Garvit Gupta
title: Garvit Gupta | Software Engineer
description: Building products that make a difference.
url: https://garvitgupta13.github.io/
baseurl: ''
email: garvitgupta2001@gmail.com
cover: https://garvitgupta13.github.io/img/og.png
logo: https://garvitgupta13.github.io/img/emojis/technologist.png
resume: https://bit.ly/garvit-gupta-resume
social:
  - title: email
    url: mailto:garvitgupta2001@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/garvitgupta13
  - title: github
    url: https://github.com/garvitgupta13/
  - title: medium
    url: https://garvitgupta13.medium.com/
  - title: leetcode
    url: https://leetcode.com/u/garvitgupta2001/
  - title: instagram
    url: https://www.instagram.com/garvitgupta_13/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
